package ddit.chap05.sec06;

public enum Day {
	MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY;
}

enum Month{
	JUNURARY, FEBRUARY, MARCHM, APRIL, MAY, JUNE, 
	JULY,AUGUST, SEPTEMBER, OCTOBER, NOVEMBER, DECEMBER;
}
